name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 18.234.85.77
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "https://github.com/Juicy321/Iot_Week9.git"
          target: "/var/www/html"